version: '2'
services:
  mongo:
    image: mongo:3.4
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/test 
     - SESSION_SECRET=tempsecret
    links:
     - mongo 
    depends_on: 
     - mongo 